apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  selector:
    app: patient-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
#  type: ClusterIP
