apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: <AWS_ECR_URL>/patient-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb+srv://kaushalya20240321:UfYI8TLMUYhQGAMm@healthsync.0xamq.mongodb.net/?retryWrites=true&w=majority&appName=HealthSync
